package stusyo222b.appz_4.template;

import stusyo222b.appz_4.entities.OfficeWorkerList;

public class MyReportPreparer extends OfficeWorkerListReportPreparer {


    @Override
    String getHeader(String filterName) {
        StringBuilder h = new StringBuilder(System.lineSeparator()+"Generated by: Yelyzaveta Syzonenko"
                +System.lineSeparator()+System.lineSeparator());
        if (!filterName.isEmpty()) {
            h.append(filterName).append(System.lineSeparator());
        }
        return h.toString();
    }

    @Override
    String getData(OfficeWorkerList list) {
        String spec = "%6s %-20s %10s %-10s %-20s"+System.lineSeparator();
        String specD = "%6s %-20s %10.2f %-10s %-20s"+System.lineSeparator();
        StringBuilder data = new StringBuilder(String.format(spec,"#","Surame","Name","WorkerCode", "Status"));
        if (!list.isEmpty()) {
            for (int number = 0;number < list.size();number++) {
                data.append(String.format(spec,number+1,list.get(number).getSurname(), list.get(number).getName(),
                        list.get(number).getWorkerCod(), list.get(number).getOfficeWorkerStatus().getDisplayName()));
            }
            data.append(System.lineSeparator());
        }
        return data.toString();
    }

    @Override
    String getFooter(String signerName) {
        return "Prepared by "+ signerName;
    }
}
